apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: crossplane
nodes:
  - role: control-plane
  - role: worker
  - role: worker
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"